# Generated by Django 4.2.23 on 2025-07-04 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_univ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univ',
            name='rank',
            field=models.IntegerField(default=417),
        ),
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.univ'),
        ),
    ]
