# Generated by Django 4.2.23 on 2025-07-04 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_univ_rank_alter_user_univ'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='univ',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='users.univ'),
        ),
    ]
