# Generated by Django 4.2.23 on 2025-07-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_univ'),
    ]

    operations = [
        migrations.AddField(
            model_name='univ',
            name='email_domain',
            field=models.CharField(default='default.ac.kr', max_length=20),
            preserve_default=False,
        ),
    ]
