# Generated by Django 4.2.23 on 2025-07-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_univ_email_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='univ',
            name='rank',
            field=models.IntegerField(default=435),
        ),
    ]
