# Generated by Django 4.2.23 on 2025-07-05 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_tempemailverification_alter_user_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TempEmailVerification',
            new_name='EmailVerification',
        ),
    ]
