# Generated by Django 5.2.4 on 2025-07-06 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_rename_tempemailverification_emailverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="univ",
            name="point",
        ),
        migrations.AddField(
            model_name="user",
            name="user_point",
            field=models.IntegerField(default=0),
        ),
    ]
