# Generated by Django 5.2.4 on 2025-07-06 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_remove_univ_point_user_user_point"),
    ]

    operations = [
        migrations.AddField(
            model_name="univ",
            name="univ_point",
            field=models.IntegerField(default=0),
        ),
    ]
