# Generated by Django 5.2.4 on 2025-07-06 08:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0003_option"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="mission",
            field=models.TextField(default="demo"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userquiz",
            name="selected_option",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_quiz",
                to="quiz.option",
            ),
        ),
    ]
