# Generated by Django 5.2.4 on 2025-07-08 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_quiz_mission_userquiz_selected_option"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name="quiz",
            name="Category",
            field=models.ManyToManyField(related_name="quizzes", to="quiz.category"),
        ),
    ]
