# Generated by Django 5.2.4 on 2025-07-08 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0005_category_quiz_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="Category",
        ),
    ]
