# Generated by Django 4.2.23 on 2025-07-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quiz_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
