# Generated by Django 4.2.23 on 2025-07-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='writer',
        ),
        migrations.RenameField(
            model_name='feed',
            old_name='author',
            new_name='writer',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='end_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='start_at',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
