# Generated by Django 4.2.23 on 2025-07-06 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_rename_author_comment_writer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='end_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='start_at',
        ),
    ]
