# Generated by Django 4.2.23 on 2025-07-06 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_remove_challenge_end_at_remove_challenge_start_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='participant_num',
            field=models.IntegerField(default=1),
        ),
    ]
