# Generated by Django 4.2.23 on 2025-07-10 15:15

import challenges.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_alter_challenge_participant_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='image',
        ),
        migrations.CreateModel(
            name='FeedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=challenges.models.upload_filepath)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='challenges.feed')),
            ],
        ),
    ]
